// <auto-generated />
using CoreFinance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MigrationTools.Migrations
{
    [DbContext(typeof(FinanceContext))]
    [Migration("20181005203057_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<string>("Uuid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<string>("PropertyUuid");

                    b.Property<string>("Username");

                    b.HasKey("Uuid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
